# Generated by Django 4.0.1 on 2022-01-17 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_app', '0002_productfree_name_productfree_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPaid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('desc', models.TextField()),
                ('img', models.ImageField(upload_to='picture')),
                ('stock', models.IntegerField()),
                ('available', models.BooleanField()),
                ('price', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_app.categ')),
            ],
        ),
    ]
