# Generated by Django 4.0.1 on 2022-01-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_delete_itemspaid'),
        ('e_app', '0003_productpaid'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfree',
            name='paid_or_free',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProductPaid',
        ),
    ]
