# Generated by Django 4.0.1 on 2022-01-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_app', '0004_productfree_paid_or_free_delete_productpaid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfree',
            name='paid_or_free',
            field=models.TextField(),
        ),
    ]
