# Generated by Django 4.0.1 on 2022-01-18 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_app', '0003_productpaid'),
        ('cart', '0002_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsFree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantF', models.IntegerField()),
                ('productF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_app.productfree')),
            ],
        ),
        migrations.CreateModel(
            name='ItemsPaid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantP', models.IntegerField()),
                ('productP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_app.productpaid')),
            ],
        ),
        migrations.DeleteModel(
            name='Items',
        ),
    ]
