# Generated by Django 4.0.1 on 2022-01-18 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_itemsfree_itemspaid_delete_items'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemsPaid',
        ),
    ]
