# Generated by Django 4.0.1 on 2022-01-19 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_itemsfree_active_itemsfree_cartf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemsfree',
            old_name='cartF',
            new_name='cart',
        ),
    ]
